config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :states, only: [:index, :show]
  resources :counties, only: [:index, :show]
  resources :zips, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state

  def name
    county
  end

  def self.premature_death
    County.select('id, measure_1_value AS raw_value, county, state_id').where('measure_1_value > 0').order('measure_1_value DESC').limit(10)
  end

  def self.low_birth_weight
    County.select('id, measure_37_value AS raw_value, county, state_id').where('measure_37_value > 0').order('measure_37_value DESC').limit(10)
  end

  def self.diabetes
    County.select('id, measure_60_value AS raw_value, county, state_id').where('measure_60_value > 0').order('measure_60_value DESC').limit(10)
  end
end

app/models/detail_card_item.rb
class DetailCardItem
  include ActionView::Helpers::NumberHelper

  attr_reader :name,
              :value

  def initialize(name, value)
    @name = name
    @value = value
  end

  def percent
    @value = "#{(@value.to_f * 100).round(2)}%"
    self
  end

  def round(places)
    @value = @value.round(places)
    self
  end

  def delimiter
    @value = number_with_delimiter(@value)
    self
  end

  def currency
    @value = number_to_currency(@value)
    self
  end
end

app/models/state.rb
class State < ApplicationRecord
  include IrsModelMethods

  validates_presence_of :abbreviation
  has_many :zips
  has_many :counties

  def high_incomes
    zips.select('zips.id, zips.a00100, zips.n1, (zips.a00100::float / zips.n1::float) AS raw_value').order('raw_value DESC').limit(10)
  end

  def low_incomes
    zips.select('zips.id, zips.a00100, zips.n1, (zips.a00100::float / zips.n1::float) AS raw_value').order('raw_value ASC').limit(10)
  end

  def self.highest_incomes
    select('states.id, states.abbreviation, states.name, states.a00100, states.n1, (states.a00100::float / states.n1::float) AS raw_value').order('raw_value DESC').limit(10)
  end

  def self.lowest_incomes
    select('states.id, states.name, states.abbreviation, states.a00100, states.n1, (states.a00100::float / states.n1::float) AS raw_value').order('raw_value ASC').limit(10)
  end

  def self.highest_pops
    select('id, name, abbreviation, n1 AS raw_value').order('raw_value DESC').limit(10)
  end

  # for income card polymorphism
  def code
    name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/zip.rb
class Zip < ApplicationRecord
  include IrsModelMethods
  validates_presence_of :n1

  belongs_to :state

  def code
    '%05d' % id
  end

  def self.highest_incomes
    select('zips.id, zips.a00100, zips.n1, (zips.a00100::float / zips.n1::float) AS raw_value').order('raw_value DESC').limit(10)
  end

  def self.lowest_incomes
    select('zips.id, zips.a00100, zips.n1, (zips.a00100::float / zips.n1::float) AS raw_value').order('raw_value ASC').limit(10)
  end

  def self.highest_pops
    select('id, n1 AS raw_value').order('raw_value DESC').limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  # def current_user
  #   if session[:user_id]
  #     id = session[:user_id]
  #     if User.exists?(id)
  #       @current_user ||= User.find(id)
  #     end
  #   end
  # end
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  def show
    @presenter = CountyPresenter.new(params[:id], current_user)
  end

  def index
    @presenter = CountyIndexPresenter.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end

  def new
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @presenter = StateIndexPresenter.new(current_user)
  end

  def show
    @presenter = StatePresenter.new(params[:id], current_user)
  end
end

app/controllers/zips_controller.rb
class ZipsController < ApplicationController
  def index
    @presenter = ZipsIndexPresenter.new(current_user)
    # render streams: true # yield, content_for... in layout
  end

  def show
    # 81642
    @presenter = ZipPresenter.new(params[:id], current_user)
  end
end

app/views/counties/index.html.erb
<h3 class="center base-card">Counties</h3>

<div class="row">
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card1 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card2 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card3 } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<!-- <script> set pd lbw, d </script> -->
<%= render partial: 'partials/map' %>

app/views/counties/show.html.erb
<h3 class="center"><%= @presenter.name %></h3>
<h5 class="center">Located in: <%= link_to @presenter.state.name, state_path(@presenter.state) %></h5>

<div class="row">
  <%= render partial: 'partials/detail_card', locals: { data: @presenter.health_card } %>
  <%= render partial: 'partials/detail_card', locals: { data: @presenter.socio_economic_card } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<%= render partial: "partials/map" %>

app/views/home/index.html.erb
</div>
<section class="slider">
  <ul class="slides">
    <li>
      <%= image_tag('kalen-emsley-Bkci_8qcdvQ-unsplash.jpg') %>
      <div class="caption center-align">
        <h3 class="slid-text">Analyze geographic information</h3>
        <h5 class="slid-text hide-on-small-only">Leverage the power of data to make better decisions and support your organization.</h5>
      </div>
    </li>
    <li>
      <%= image_tag('pierre-blache-VMNG8BYFQfs-unsplash.jpg') %>
      <div class="caption left-align">
        <h3 class="slid-text">Visualize demographics in your area</h3>
        <h5 class="slid-text hide-on-small-only">Use our statistics, charts, and maps to better target your campaigns.</h5>
      </div>
    </li>
    <li>
      <%= image_tag('joonyeop-baek-1kf69eE7VR4-unsplash.jpg') %>
      <div class="caption right-align">
        <h3 class="slid-text">Use data to do good</h3>
        <h5 class="slid-text hide-on-small-only">More effectively target your resources to get the maximum effect.</h5>
      </div>
    </li>
  </ul>
</section>
<div class=container>
<h3 class="center">Welcome to AnalyZip</h3>
<p class="flow-text">We aim to allow non-profits access to a wide range of data with an easy to use interface to help them improve their decision making and do more good in their communities. Zip codes are convienient geographic entities with a wealth of public data available for each one of the over 27,000 in the United States. Our site pulls data from the IRS and other sources, and makes the data easily readable, searchable, and connected to Google Maps. We hope this service empowers you to assist those in your community and across the country.</p>

<hr>

  <%= render partial: 'partials/login' %>

<script>
  const slider = document.querySelector('.slider');
  M.Slider.init(slider, {
    indicators: false,
    height: 500,
    transition: 500,
    interval: 5000
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @presenter.page_title %></title>
    <meta name="description" content="<%= @presenter.page_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <%= favicon_link_tag asset_path('favicon.svg') %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script src="https://cdn.usefathom.com/script.js" data-site="ADBFFAKL" defer></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  <div class="navbar-fixed">
    <nav class="teal darken-4">
      <div class="container">
        <div class="nav-wrapper">
          <%= link_to image_tag('AnalyZip.svg', alt: 'AnalyZip', width: 145, class: 'az-logo'), root_path, class: 'brand-logo' %>
          <a href="#" data-target="mobile-nav" class="sidenav-trigger">
            <i class="material-icons">menu</i>
          </a>
          <ul class="right hide-on-med-and-down">
            <li><%= link_to @presenter.user_action, @presenter.current_user_path %></li>
            <li><%= link_to @presenter.log_action, @presenter.log_path %></li>
            <li><%= link_to 'States', states_path %></li>
            <li><%= link_to 'Counties', counties_path %></li>
            <li><%= link_to 'Zip Codes', zips_path %></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <ul class="sidenav" id="mobile-nav">
    <li><%= link_to @presenter.user_action, @presenter.current_user_path %></li>
    <li><%= link_to @presenter.log_action, @presenter.log_path %></li>
    <li><%= link_to 'States', states_path %></li>
    <li><%= link_to 'Counties', counties_path %></li>
    <li><%= link_to 'Zip Codes', zips_path %></li>
  </ul>

  <div class="container">
    <%= yield %>
  </div>

  <footer class="teal darken-4 white-text center">
    <p>AnalyZip</p>
  </footer>

  <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/partials/_detail_card.html.erb
<div class="col s12 m4">
  <div class="card-panel grey lighten-5 hoverable <%= data.css_name %>">
    <h5 class="center teal-text text-darken-4"><%= data.title %></h5>
    <% data.each do |item| %>
      <p><%= item.name %>: <span class="right"><%= item.value %></span></p>
    <% end %>
  </div>
</div>

app/views/partials/_fav_add.html.erb
<%= form_for @presenter.favorite do |f| %>
<%= f.label :comment %>
<%= f.text_field :comment, oninput: 'changeSubmit()' %>
<%= f.hidden_field :zip_id, value: @presenter.code %>
<%= f.submit @presenter.fav_submit_message, id: 'fav_submit', onclick: 'submitClick()' %>
<% end %>

<%= button_to 'Delete', "/user_zips/#{@presenter.favorite.id}", method: :delete, id: 'delete-button', onclick: 'deleteClick()' %>


<% if @presenter.favorite.persisted? %>
  <script>
    var shouldDelete = true
    const deleteButton = document.querySelector('#delete-button')
    deleteButton.style.visibility = "hidden"
    const favSubmit = document.querySelector('#fav_submit')

    function submitClick() {
      if(shouldDelete) {
        event.preventDefault()
        deleteButton.click()
      }
    }

    function deleteClick() {
      console.log("delete")
    }

    function changeSubmit() {
      favSubmit.value = "Update comment"
      shouldDelete = false
    }

  </script>
<% else %>
  <script>
    const deleteButton = document.querySelector('#delete-button')
    deleteButton.style.visibility = "hidden"
  </script>
<% end %>

app/views/partials/_fav_login.html.erb
<%= link_to 'Login or Sign Up to add this zip to my favorites', '/Login' %>

app/views/partials/_login.html.erb
<h5 class='center'>Sign in for added features</h5>

<div class='social-logins center'>
  <form method="get" action='/auth/google'>
    <button type='submit' class='google-button center hoverable'><div class='google-button-div valign-wrapper'>
      <%= image_tag('btn_google_dark_normal_ios.svg') %>
      <div class='google-button-text'>Sign in with Google</div>
    </div>
  </button>
</form>
</div>

app/views/partials/_map.html.erb
<% if @presenter.lat %>
<!-- if there is a valid map -->

<script>
  const lat = <%= @presenter.lat %>;
  const lng = <%= @presenter.lng %>;
  const ne_lat = <%= @presenter.ne_lat %>;
  const ne_lng = <%= @presenter.ne_lng %>;
  const sw_lat = <%= @presenter.sw_lat %>;
  const sw_lng = <%= @presenter.sw_lng %>;
  const title = "<%= @presenter.map_name %>"
  const geoUnit = "<%= @presenter.geo_unit %>"

  var card1Items = [];
  var card2Items = [];
  var card3Items = [];

  <% @presenter.card1.each do |location| %>
    card1Items.push("<%= location.name %>")
    console.log(location);
  <% end %>
  var card1Title = "<%= @presenter.card1.title %>"

  <% @presenter.card2.each do |location| %>
    card2Items.push("<%= location.name %>")
  <% end %>
  var card2Title = "<%= @presenter.card2.title %>"

  <% @presenter.card3.each do |location| %>
    card3Items.push("<%= location.name %>")
  <% end %>
  var card3Title = "<%= @presenter.card3.title %>"

</script>

<%= javascript_include_tag 'maps' %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.google[:api_key]}&callback=initMap", async: true, defer: true %>
<% else %>
  <!-- if no valid map -->
  <script>
    const map = document.querySelector("#map")
    map.style.display = 'hidden'
  </script>
<% end %>

app/views/partials/_ranking_card.html.erb
<div class="col s12 m4">
  <div class="card-panel grey lighten-5 hoverable <%= data.css_name %>">
    <h5 class="center teal-text text-darken-4"><%= data.title %>:</h5>
    <ol>
      <% data.each do |item| %>
      <li><%= link_to item.link_name, item.path %>: <span class="right"><%= item.value %></span></li>
      <% end %>
    </ol>
  </div>
</div>

app/views/states/index.html.erb
<h3 class="center base-card">States</h3>

<div class="row">
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card1 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card2 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card3 } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<h5 class="center">All States</h5>
<div class='all-states'>
<% @presenter.states.each do |state| %>
   <%= link_to state.name, state_path(state), class: 'state-link' %>
<% end %>
</div>

<%= render partial: 'partials/map' %>

app/views/states/show.html.erb
<h3 class="center"><%= @presenter.name %></h3>

<div class="row">
  <%= render partial: 'partials/detail_card', locals: { data: @presenter.basic_irs_card } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card2 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card3 } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<h5 class="center">Zip Codes in <%= @presenter.name %></h5>
<% @presenter.zips.each do |zip| %>
  <%= link_to zip.code, zip_path(zip) %>
<% end %>

<h5 class="center">Counties in <%= @presenter.name %></h5>
<% @presenter.counties.each do |county| %>
  <%= link_to county.name, county_path(county) %>
<% end %>

<%= render partial: 'partials/map' %>

app/views/users/show.html.erb
<h3 class='center'>Welcome, <%= @presenter.first_name %></h3>

<ul>
  <% @presenter.user_zips.each do |user_zip| %>
    <li><%= link_to user_zip.zip.code, zip_path(user_zip.zip_id) %>: <%= user_zip.comment %></li>
  <% end %>
</ul>

app/views/zips/index.html.erb
<h3 class="center base-card">Zip Codes</h3>

<div class="row">
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card1 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card2 } %>
  <%= render partial: 'partials/ranking_card', locals: { data: @presenter.card3 } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<!-- <script> set pd lbw, d </script> -->
<%= render partial: 'partials/map' %>

app/views/zips/show.html.erb
<h3 class="center"><%= @presenter.code %></h3>
<h5 class="center">Located in: <%= link_to @presenter.state_name, state_path(@presenter.state) %></h5>

<%= render partial: "/partials/#{@presenter.fav_partial}" %>

<div class="row">
  <%= render partial: 'partials/detail_card', locals: { data: @presenter.basic_irs_card } %>
</div>

<div id="map-info"></div>
<div id="map"></div>

<%= render partial: 'partials/map' %>